kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: chfs-data
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi    #----------上面创建的存储类的名称
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
