apiVersion: v1
kind: Service
metadata:
 name: chfs
spec:
 type: NodePort
 ports:
  - name: http
    port: 8080
    nodePort: 31001
  # - name: https
  #   port: 37000
  #   nodePort: 37000
 selector:
   app: chfs